### ISSUE TITLE
No pagination

### ISSUE THREAD

**Issue by claytonman** [epilocal/newsliner#2]
I couldn't find pagination and the theme can only display several posts on the landing page like this: https://1082.xyz/. Am I missing something here? Pagination feature is a must-have for any blog theme.

**Comment by claytonman** [comment]
Guess the `index.hbs` needs some changes?

```html
              {{!-- Filter to get 2 most recent Featured posts --}}
              {{#get "posts" limit="2" include="tags,authors" filter="featured:true" as |featuredPosts|}}
              {{!-- Filter to get 4 most recent non-Featured posts --}}
              {{#get "posts" limit="4" include="tags,authors" filter="featured:false" as |nonFeaturedPosts|}}
                {{!-- Full-screen post-card-large for Featured post - partials/post-card.hbs --}}
                 {{#foreach featuredPosts visibility="all" limit="1"}}
                    {{> "post-card" post_large=true}}
                 {{/foreach}}
                 {{!-- Half-screen post-card for 2 non-Featured posts - partials/post-card.hbs --}}
                 {{#foreach nonFeaturedPosts visibility="all" limit="2" from="1" to="2"}}
                    {{> "post-card"}}
                 {{/foreach}}
                 {{!-- Full-screen post-card-large for Featured post - partials/post-card.hbs --}}
                 {{#foreach featuredPosts visibility="all" limit="1" from="2" to="2" }}
                    {{> "post-card" post_large=true}}
                 {{/foreach}}
                 {{!-- Half-screen post-card for 2 non-Featured posts - partials/post-card.hbs --}}
                 {{#foreach nonFeaturedPosts visibility="all" limit="2" from="3" to="4" }}
                    {{> "post-card"}}
                 {{/foreach}}
              {{/get}}
              {{/get}}
```

**Comment by claytonman** [comment]
I did a temp fix myself by changing the value in the filter in `index.hbs` from `4` to `10` so my website is displayed properly now: https://1082.xyz, but this is hardly an elegant permanent solution.

**Comment by gjdickens** [comment]
Thanks for checking out the theme!

There was a bit of a trade-off here on the `index.hbs` page:  I had originally used custom queries to force a pattern of 1 featured story, 2 non-featured, 1 featured, 2 non-featured... but using custom queries breaks Ghost's pagination.

I've updated the theme now so that it has pagination on `index.hbs` and the posts are simply displayed in the order that you publish them.  The downside to this is that if you post 1 non-featured and then 1 featured,, the unfeatured post will have a small post-card on a single line... so keep in mind you will want to always have an even number of unfeatured posts between featured posts.

**Comment by claytonman** [comment]
Thanks for the fix!

Understand the trade-off. Appreciate the update to add on pagination.
